export { default as SectionGeneralAbout } from '@/components/sections/general/SectionGeneralAbout'
export { default as SectionGeneralGeography } from '@/components/sections/general/SectionGeneralGeography'
export { default as SectionGeneralPartners } from '@/components/sections/general/SectionGeneralPartners'
export { default as SectionGeneralProducts } from '@/components/sections/general/SectionGeneralProducts'
export { default as SectionGeneralServices } from '@/components/sections/general/SectionGeneralServices'
