// ./general
export type { default as TGeneralChildren } from '@/types/general/TGeneralChildren'
export type { default as TGeneralClassNames } from '@/types/general/TGeneralClassNames'
export type { default as TGeneralColorHex } from '@/types/general/TGeneralColorHex'
export type { default as TGeneralColorKeys } from '@/types/general/TGeneralColorKeys'
export type { default as TGeneralDataUrl } from '@/types/general/TGeneralDataUrl'
export type { default as TGeneralElId } from '@/types/general/TGeneralElId'
export type { default as TGeneralH } from '@/types/general/TGeneralH'
export type { default as TGeneralRoute } from '@/types/general/TGeneralRoute'
export type { default as TGeneralTitle } from '@/types/general/TGeneralTitle'

// ./img
export type { default as TImgAlt } from '@/types/img/TImgAlt'
export type { default as TImgHeight } from '@/types/img/TImgHeight'
export type { default as TImgPriority } from '@/types/img/TImgPriority'
export type { default as TImgSrc } from '@/types/img/TImgSrc'
export type { default as TImgUnoptimized } from '@/types/img/TImgUnoptimized'
export type { default as TImgWidth } from '@/types/img/TImgWidth'

// ./props
export type { default as TPropBgc } from '@/types/props/TPropBgc'
export type { default as TPropChildren } from '@/types/props/TPropChildren'
export type { default as TPropClassNames } from '@/types/props/TPropClassNames'
export type { default as TPropClose } from '@/types/props/TPropClose'
export type { default as TPropColor } from '@/types/props/TPropColor'
export type { default as TPropElId } from '@/types/props/TPropElId'
export type { default as TPropH1 } from '@/types/props/TPropH1'
export type { default as TPropImgAlt } from '@/types/props/TPropImgAlt'
export type { default as TPropImgHeight } from '@/types/props/TPropImgHeight'
export type { default as TPropImgPriority } from '@/types/props/TPropImgPriority'
export type { default as TPropImgSrc } from '@/types/props/TPropImgSrc'
export type { default as TPropImgUnoptimized } from '@/types/props/TPropImgUnoptimized'
export type { default as TPropImgWidth } from '@/types/props/TPropImgWidth'
export type { default as TPropLinkLocale } from '@/types/props/TPropLinkLocale'
export type { default as TPropOpen } from '@/types/props/TPropOpen'
export type { default as TPropStyledAsH2 } from '@/types/props/TPropStyledAsH2'
export type { default as TPropTitle } from '@/types/props/TPropTitle'
